class AppLocale {
  final String adbSuite;
  final String analyzeApk;
  final String signerSuite;
  final String devTools;
  final String settings;
  final String screenMirror;
  final String statusConnected;
  final String statusDisconnected;
  final String statusError;
  final String appTitle;
  final String selectApk;
  final String analyzing;
  final String fastInstall;
  final String install;
  final String delete;
  final String packageToDelete;
  final String language;
  final String theme;
  final String about;
  final String version;
  final String developedBy;
  final String copySuccess;
  final String keyAlias;
  final String password;
  final String organization;
  final String createJks;
  final String apkSigner;
  final String jarSigner;
  final String debugRun;
  final String releaseBuild;
  final String darkMode;
  final String lightMode;
  final String rebootPos;
  final String confirmReboot;
  final String toolsLoaded;
  final String autoDetect;
  final String exitCode;
  final String apkSelected;
  final String searchHint;
  final String filter;
  final String startStream;
  final String stopStream;
  final String clearLogs;
  final String saveLogs;
  final String signingManagement;
  final String signApk;
  final String creationCardTitle;
  final String newJks;
  final String apkSelectedTitle;
  final String pickApk;
  final String pickJks;
  final String aliasLabel;
  final String passwordLabel;
  final String ownerInfo;
  final String fullName;
  final String department;
  final String company;
  final String city;
  final String state;
  final String countryCode;
  final String generateJks;
  final String sign;
  final String cancel;
  final String ready;
  final String success;
  final String error;
  final String copySn;
  final String connectionStatus;
  final String selectTerminalTooltip;
  final String validAndroid;
  final String validMaxStore;
  final String invalidUnsigned;
  final String signError;
  final String jksSaved;
  final String jksError;
  final String apkSaved;
  final String missingData;
  final String browse;
  final String signingApp;
  final String signingCredentials;
  final String selectApkHint;
  final String selectJksHint;
  final String loading;
  final String unavailable;
  final String close;
  final String architecture;
  final String filename;
  final String schemes;
  final String signature;
  final String viewCommands;
  final String analyzeAnotherApk;
  final String clickToCopy;
  final String clearScreen;
  final String autoScroll;
  final String saveLog;
  final String configSdk;
  final String readyToStart;
  final String jksFileLabel;
  final String aliasHint;
  final String min6Chars;
  final String repeatPassword;
  final String confirmPassword;
  final String ownerDetails;
  final String certFieldsNote;
  final String copyIcon;
  final String copyPackage;
  final String copyName;
  final String updateTooltip;
  final String signTooltip;
  final String certificate;
  final String sha256;
  final String noIcon;
  final String iconCopied;
  final String iconCopyError;
  final String iconCriticalError;
  final String copied;
  final String splashLoading;
  final String analysisInitialTitle;
  final String analysisInitialDesc;
  final String pleaseWait;
  final String appAlreadyInstalled;
  final String installApkTooltip;
  final String uninstallApkTooltip;
  final String uninstallAnyAppTooltip;
  final String appNotInstalled;
  final List<String> splashMessages;
  final Map<String, String> translations;

  AppLocale({
    required this.adbSuite,
    required this.analyzeApk,
    required this.signerSuite,
    required this.devTools,
    required this.settings,
    required this.screenMirror,
    required this.statusConnected,
    required this.statusDisconnected,
    required this.statusError,
    required this.appTitle,
    required this.selectApk,
    required this.analyzing,
    required this.fastInstall,
    required this.install,
    required this.delete,
    required this.packageToDelete,
    required this.language,
    required this.theme,
    required this.about,
    required this.version,
    required this.developedBy,
    required this.copySuccess,
    required this.keyAlias,
    required this.password,
    required this.organization,
    required this.createJks,
    required this.apkSigner,
    required this.jarSigner,
    required this.debugRun,
    required this.releaseBuild,
    required this.darkMode,
    required this.lightMode,
    required this.rebootPos,
    required this.confirmReboot,
    required this.toolsLoaded,
    required this.autoDetect,
    required this.exitCode,
    required this.apkSelected,
    required this.searchHint,
    required this.filter,
    required this.startStream,
    required this.stopStream,
    required this.clearLogs,
    required this.saveLogs,
    required this.signingManagement,
    required this.signApk,
    required this.creationCardTitle,
    required this.newJks,
    required this.apkSelectedTitle,
    required this.pickApk,
    required this.pickJks,
    required this.aliasLabel,
    required this.passwordLabel,
    required this.ownerInfo,
    required this.fullName,
    required this.department,
    required this.company,
    required this.city,
    required this.state,
    required this.countryCode,
    required this.generateJks,
    required this.sign,
    required this.cancel,
    required this.ready,
    required this.success,
    required this.error,
    required this.copySn,
    required this.connectionStatus,
    required this.selectTerminalTooltip,
    required this.validAndroid,
    required this.validMaxStore,
    required this.invalidUnsigned,
    required this.signError,
    required this.jksSaved,
    required this.jksError,
    required this.apkSaved,
    required this.missingData,
    required this.browse,
    required this.signingApp,
    required this.signingCredentials,
    required this.selectApkHint,
    required this.selectJksHint,
    required this.loading,
    required this.unavailable,
    required this.close,
    required this.architecture,
    required this.filename,
    required this.schemes,
    required this.signature,
    required this.viewCommands,
    required this.analyzeAnotherApk,
    required this.clickToCopy,
    required this.clearScreen,
    required this.autoScroll,
    required this.saveLog,
    required this.configSdk,
    required this.readyToStart,
    required this.jksFileLabel,
    required this.aliasHint,
    required this.min6Chars,
    required this.repeatPassword,
    required this.confirmPassword,
    required this.ownerDetails,
    required this.certFieldsNote,
    required this.copyIcon,
    required this.copyPackage,
    required this.copyName,
    required this.updateTooltip,
    required this.signTooltip,
    required this.certificate,
    required this.sha256,
    required this.noIcon,
    required this.iconCopied,
    required this.iconCopyError,
    required this.iconCriticalError,
    required this.copied,
    required this.splashLoading,
    required this.analysisInitialTitle,
    required this.analysisInitialDesc,
    required this.pleaseWait,
    required this.appAlreadyInstalled,
    required this.installApkTooltip,
    required this.uninstallApkTooltip,
    required this.uninstallAnyAppTooltip,
    required this.appNotInstalled,
    required this.splashMessages,
    required this.translations,
  });

  static AppLocale get(String code) {
    return languages[code] ?? languages['en']!;
  }

  static final Map<String, AppLocale> languages = {
    'es': AppLocale(
      adbSuite: 'Suite ADB',
      analyzeApk: 'Analizar APK',
      signerSuite: 'Gestión de Firma',
      devTools: 'Herramientas Dev',
      settings: 'Opciones',
      screenMirror: 'Espejo de Pantalla',
      statusConnected: 'Conectado',
      statusDisconnected: 'Desconectado',
      statusError: 'Error',
      appTitle: 'ISV TOOLKIT',
      selectApk: 'Seleccionar APK para analizar',
      analyzing: 'Analizando...',
      fastInstall: 'Instalación Rápida',
      install: 'INSTALAR',
      delete: 'DESINSTALAR',
      packageToDelete: 'Paquete para desinstalar',
      language: 'Idioma',
      theme: 'Tema',
      about: 'Acerca de',
      version: 'Versión',
      developedBy: 'Desarrollado por iOnetech',
      copySuccess: 'copiado',
      keyAlias: 'Alias de Llave',
      password: 'Contraseña',
      organization: 'Organización',
      createJks: 'NUEVO JKS',
      apkSigner: 'APK-SIGNER',
      jarSigner: 'JAR-SIGNER',
      debugRun: 'PROYECTO (DEBUG)',
      releaseBuild: 'EXE (RELEASE)',
      darkMode: 'Modo Oscuro',
      lightMode: 'Modo Claro',
      rebootPos: 'Reiniciar POS',
      confirmReboot: '¿Estás seguro de que deseas reiniciar el POS?',
      toolsLoaded: 'Herramientas cargadas',
      autoDetect: 'AUTO-DETECCIÓN',
      exitCode: 'Código de salida',
      apkSelected: 'APK Seleccionado',
      searchHint: 'Buscar...',
      filter: 'FILTROS',
      startStream: 'INICIAR',
      stopStream: 'DETENER',
      clearLogs: 'LIMPIAR',
      saveLogs: 'Guardar Logcat',
      signingManagement: 'Gestión de Firma',
      signApk: 'Firmar APK',
      creationCardTitle: 'CONFIGURACIÓN JKS',
      newJks: 'Crear JKS',
      apkSelectedTitle: 'APK Seleccionado',
      pickApk: 'Explorar',
      pickJks: 'Seleccionar Almacén',
      aliasLabel: 'Alias de la Llave',
      passwordLabel: 'Contraseña del Almacén',
      ownerInfo: 'INFORMACIÓN DEL PROPIETARIO',
      fullName: 'Nombre Completo',
      department: 'Departamento',
      company: 'Empresa',
      city: 'Ciudad',
      state: 'Estado/Provincia',
      countryCode: 'Código País (CL, US...)',
      generateJks: 'Generar JKS',
      sign: 'Firmar',
      cancel: 'Cancelar',
      ready: 'Listo para iniciar',
      success: 'Éxito',
      error: 'Error',
      copySn: 'Click para copiar S/N',
      connectionStatus: 'Estado de conexión',
      selectTerminalTooltip: 'Seleccionar Terminal',
      validAndroid: 'Válida (Predeterminada de Android)',
      validMaxStore: 'Válida (Compatible con MaxStore)',
      invalidUnsigned: 'Inválida / Sin firmar',
      signError: 'Error al firmar',
      jksSaved: 'JKS guardado en:',
      jksError: 'Error al crear JKS',
      apkSaved: 'Guardado en:',
      missingData: 'Faltan datos requeridos (APK, JKS o Contraseña).',
      browse: 'Explorar',
      signingApp: 'Firmar Aplicación',
      signingCredentials: 'Credenciales de Firma',
      selectApkHint: 'Selecciona un archivo APK',
      selectJksHint: 'Seleccionar .jks o .keystore...',
      loading: 'Cargando...',
      unavailable: 'No disponible',
      close: 'CERRAR',
      architecture: 'Arquitectura',
      filename: 'Nombre Archivo',
      schemes: 'Esquemas',
      signature: 'Firma',
      viewCommands: 'Ver comandos utilizados',
      analyzeAnotherApk: 'Analizar otra APK',
      clickToCopy: 'Click para copiar',
      clearScreen: 'Limpiar Pantalla',
      autoScroll: 'Auto-scroll',
      saveLog: 'Guardar Log',
      configSdk: 'Configuración SDK',
      readyToStart: 'Listo para iniciar',
      jksFileLabel: 'Nombre archivo (.jks)',
      aliasHint: 'Predeterminado: key0',
      min6Chars: 'Mínimo 6 caracteres',
      repeatPassword: 'Repite la contraseña',
      confirmPassword: 'Confirmar Contraseña',
      ownerDetails: 'DETALLES DEL PROPIETARIO',
      certFieldsNote:
          '* Estos campos aparecerán en el certificado digital de la APK.',
      copyIcon: 'Click para copiar icono',
      copyPackage: 'Click para copiar Package Name',
      copyName: 'Click para copiar nombre',
      updateTooltip: 'Actualizar a la versión de la APK',
      signTooltip: 'Firmar esta APK',
      certificate: 'Certificado',
      sha256: 'SHA-256',
      noIcon: 'Sin icono',
      iconCopied: 'Icono copiado al portapapeles',
      iconCopyError: 'Error al copiar icono',
      iconCriticalError: 'Error crítico al copiar icono',
      copied: 'Copiado',
      splashLoading: 'Iniciando sistema...',
      analysisInitialTitle: 'Análisis de APK',
      analysisInitialDesc:
          'Selecciona o arrastra una APK para comenzar el análisis técnico.',
      pleaseWait: 'Por favor, espere...',
      appAlreadyInstalled: 'La app ya está instalada',
      installApkTooltip: 'Instalar APK en el dispositivo',
      uninstallApkTooltip: 'Desinstalar app del dispositivo',
      uninstallAnyAppTooltip: 'Desinstalar cualquier app del dispositivo',
      appNotInstalled: 'La app no está instalada',
      splashMessages: [
        'Cargando módulos de ADB...',
        'Iniciando suite de análisis...',
        'Configurando herramientas de firma...',
        'Verificando conexión con dispositivos...',
        'Preparando entorno de trabajo...',
      ],
      translations: {
        "Español": "Español",
        "English": "English",
        "Português": "Português",
        "Configuración de Rutas": "Configuración de Rutas",
        "Recargar": "Recargar",
        "Estadísticas": "Estadísticas",
        "Buscar (mín. 3 letras)...": "Buscar (mín. 3 letras)...",
        "FILTRAR POR PACKAGE:": "FILTRAR POR PACKAGE:",
        "Desinstalar app del dispositivo": "Desinstalar app del dispositivo",
        "La app no está instalada": "La app no está instalada",
        "Cargando...": "Cargando...",
        "No disponible": "No disponible",
        "INSTALAR": "INSTALAR",
        "DESINSTALAR": "DESINSTALAR",
        "INSTALANDO...": "INSTALANDO...",
        "DESINSTALANDO...": "DESINSTALANDO...",
        "ACTUALIZAR": "ACTUALIZAR",
        "ACTUALIZANDO...": "ACTUALIZANDO...",
        "Instalada": "Instalada",
        "No instalada": "No instalada",
        "FIRMAR": "FIRMAR",
        "ESPECIFICACIONES": "ESPECIFICACIONES",
        "VERIFICACIÓN DE SEGURIDAD": "VERIFICACIÓN DE SEGURIDAD",
        "LOGCAT MONITOR": "LOGCAT",
        "INICIAR STREAM": "INICIAR",
        "DETENER": "DETENER",
        "LIMPIAR": "LIMPIAR",
        "FILTROS": "FILTROS",
        "Guardar Logcat": "Guardar Logcat",
        "Seleccionar APK para analizar": "Seleccionar APK para analizar",
        "Analizando...": "Analizando...",
        "Limpiar análisis": "Limpiar análisis",
        "Comandos de Análisis": "Comandos de Análisis",
        "CERRAR": "CERRAR",
        "ESTADÍSTICAS EN VIVO": "ESTADÍSTICAS EN VIVO",
        "Selecciona un paquete": "Selecciona un paquete",
        "NUEVO JKS": "NUEVO JKS",
        "Monitoreo: ACTIVO": "Monitoreo: ACTIVO",
        "Monitoreo: INACTIVO": "Monitoreo: INACTIVO",
        "Herramientas cargadas": "Herramientas cargadas",
        "AUTO-DETECCIÓN": "AUTO-DETECCIÓN",
        "BUSCAR SDK": "BUSCAR SDK",
        "Confirmar Reinicio": "Confirmar Reinicio",
        "¿Estás seguro de que deseas reiniciar el POS vinculado por ADB?":
            "¿Estás seguro de que deseas reiniciar el POS vinculado por ADB?",
        "CANCELAR": "CANCELAR",
        "REINICIAR": "REINICIAR",
        "Alias de la Llave": "Alias de la Llave",
        "Contraseña del Almacén": "Contraseña del Almacén",
        "JKS creado con éxito": "JKS creado con éxito",
        "Error al crear JKS": "Error al crear JKS",
        "Comando de reinicio enviado": "Comando de reinicio enviado",
        "Error al intentar reiniciar el terminal":
            "Error al intentar reiniciar el terminal",
        "Reiniciar Terminal": "Reiniciar Terminal",
        "Reiniciar POS conectado por ADB": "Reiniciar POS conectado por ADB",
        "Selecciona una aplicación para ver estadísticas":
            "Selecciona una aplicación para ver estadísticas",
        "TODOS (Escribe para buscar)": "TODOS (Escribe para buscar)",
        "Espejo de Pantalla": "Espejo de Pantalla",
        "Iniciar Espejo": "Iniciar Espejo",
        "Mirroring: ACTIVO": "Mirroring: ACTIVO",
        "Mirroring: INACTIVO": "Mirroring: INATIVO",
        "Descargando scrcpy...": "Descargando scrcpy...",
        "Instalando scrcpy...": "Instalando scrcpy...",
        "Herramientas Mirror cargadas": "Herramientas Mirror cargadas",
        "Descarga completada": "Descarga completada",
        "Captura de Pantalla": "Captura de Pantalla",
        "Grabando": "Grabando",
        "Iniciar Grabación": "Iniciar Grabación",
        "Detener Grabación": "Detener Grabación",
        "Captura guardada": "Captura guardada",
        "Herramientas de Terminal": "Herramientas de Terminal",
        "Confirmar desinstalación": "Confirmar desinstalación",
        "¿Desinstalar": "¿Desinstalar",
        "del dispositivo?": "del dispositivo?",
        "Desinstalado con éxito": "Desinstalado con éxito",
        "Error al desinstalar": "Error al desinstalar",
        "Cargando paquetes...": "Cargando paquetes...",
        "paquetes instalados": "paquetes instalados",
        "Verificación Jarsigner": "Verificación Jarsigner",
        "Firma Completa": "Firma Completa",
        "Sin Firmar (Unsigned)": "Sin Firmar (Unsigned)",
        "Simulador SDK": "Simulador SDK",
        "Modo de Operación": "Modo de Operación",
        "Simulador Local (MOCK)": "Simulador Local (MOCK)",
        "Terminal Físico (Vía Agente SDK)": "Terminal Físico (Vía Agente SDK)",
        "Host / IP": "Host / IP",
        "Puerto": "Puerto",
        "Puerto COM": "Puerto COM",
        "Estado del Terminal": "Estado del Terminal",
        "Consola de Logs": "Consola de Logs",
        "Respuesta del Terminal": "Respuesta del Terminal",
        "Monto": "Monto",
        "Propina": "Propina",
        "Tipo de Pago": "Tipo de Pago",
        "Cuotas": "Cuotas",
        "ID de Orden": "ID de Orden",
        "Enviar Transacción": "Enviar Transacción",
        "Limpiar": "Limpiar",
        "Historial de Operaciones": "Historial de Operaciones",
        "Conectando...": "Conectando...",
        "Espere por favor...": "Espere por favor...",
        "Monto inválido": "Monto inválido",
        "RUT inválido": "RUT inválido",
        "Transacción enviada": "Transacción enviada",
        "Ingresa el ID de la transacción a anular":
            "Ingresa el ID de la transacción a anular",
        "Última venta": "Última venta",
        "Copiar JSON": "Copiar JSON",
        "Copiar logs": "Copiar logs",
        "Venta": "Venta",
        "Anulación": "Anulación",
        "Conectar": "Conectar",
        "Desconectar": "Desconectar",
        "Número de Ticket": "Número de Ticket",
        "Tipo de Venta": "Tipo de Venta",
        "ID de Vendedor": "ID de Vendedor",
        "Imprimir en POS": "Imprimir en POS",
        "Mensajes Intermedios": "Mensajes Intermedios",
        "Timeout (segundos)": "Timeout (segundos)",
        "Test conexión (POLL)": "Test conexión (POLL)",
        "Ejecutando POLL...": "Ejecutando POLL...",
        "Ping de conexión exitoso": "Ping de conexión exitoso",
        "Error al ejecutar POLL": "Error al ejecutar POLL",
        "Última transacción": "Última transacción",
        "Firma digital": "Firma digital",
        "JSON serializado": "JSON serializado",
        "Otro...": "Otro...",
        "Mostrar lista": "Mostrar lista",
        "Devolución (103)": "Devolución (103)",
        "Pre-Autorización (104)": "Pre-Autorización (104)",
        "Confirmar Pre-Aut (105)": "Confirmar Pre-Aut (105)",
        "POLL (106)": "POLL (106)",
        "Última Transacción (108)": "Última Transacción (108)",
        "Ver Configuración (110)": "Ver Configuración (110)",
        "Reporte Propinas (111)": "Reporte Propinas (111)",
        "Saldo (112)": "Saldo (112)",
        "Totales Lote (121)": "Totales Lote (121)",
        "Detalle Transacciones (123)": "Detalle Transacciones (123)",
        "Reporte Vendedor (125)": "Reporte Vendedor (125)",
        "Modo Normal (107)": "Modo Normal (107)",
        "Cierre (120)": "Cierre (120)",
        "Inicializar (122)": "Inicializar (122)",
        "Duplicado (124)": "Duplicado (124)",
        "Parámetros (126)": "Parámetros (126)",
        "Test Comm (128)": "Test Comm (128)",
        "Bajar Llaves (130)": "Bajar Llaves (130)",
        "Transacciones": "Transacciones",
        "Consultas": "Consultas",
        "Gestión": "Gestión",
        "Monto Devolución": "Monto Devolución",
        "Monto Pre-Autorización": "Monto Pre-Autorización",
        "Monto Confirmación": "Monto Confirmación",
        "Clave (Key)": "Clave (Key)",
        "Valor (Value)": "Valor (Value)",
        "ID de Transacción Original": "ID de Transacción Original",
        "Este comando se enviará directamente al POS sin parámetros adicionales.":
            "Este comando se enviará directamente al POS sin parámetros adicionales.",
        "Enviar Comando": "Enviar Comando",
        "Protocolo Simplificado": "Protocolo Simplificado",
        "Texto a Hexadecimal": "Texto a Hexadecimal",
        "Hexadecimal a Texto": "Hexadecimal a Texto",
        "CONVERSOR / LRC": "CONVERSOR / LRC",
        "Paso 1: Seleccione la conversión": "Paso 1: Seleccione la conversión",
        "Paso 2: Ingrese la data (Excluyendo STX/ETX/LRC)":
            "Paso 2: Ingrese la data (Excluyendo STX/ETX/LRC)",
        "Paso 3: Resultado de conversión": "Paso 3: Resultado de conversión",
        "Traducción Real (Bytes de Control 0x02, 0x03)":
            "Traducción Real (Bytes de Control 0x02, 0x03)",
        "Traducción Literal (String \"<STX>\", \"<ETX>\")":
            "Traducción Literal (String \"<STX>\", \"<ETX>\")",
        "Hex copiado al portapapeles": "Hex copiado al portapapeles",
        "ENVIAR VENTA (ISO8583)": "ENVIAR VENTA (ISO8583)",
        "Enviar Venta Simplificada": "Enviar Venta Simplificada",
        "Venta aprobada en Protocolo Simplificado!":
            "Venta aprobada en Protocolo Simplificado!",
        "Venta rechazada/fallida": "Venta rechazada/fallida",
        "OPCIONES DE IMPRESIÓN": "OPCIONES DE IMPRESIÓN",
        "CONEXIÓN PUERTO SERIAL": "CONEXIÓN PUERTO SERIAL",
        "Comunicación basada en el formato ISO8583 (Pipe Separated)":
            "Comunicación basada en el formato ISO8583 (Pipe Separated)",
        "Terminal conectado en": "Terminal conectado en",
        "Error al conectar en": "Error al conectar en",
        "Debe conectar el puerto COM primero.":
            "Debe conectar el puerto COM primero.",
        "Código": "Código",
        "ENVIAR COMANDO (ISO8583)": "ENVIAR COMANDO (ISO8583)",
        "Comando a enviar": "Comando a enviar",
        "Enviar Comando Simplificado": "Enviar Comando Simplificado",
        "Usar última venta": "Usar última venta",
        "Comando rechazado/fallido": "Comando rechazado/fallido",
        "Realizar una venta cobrando al cliente":
            "Realizar una venta cobrando al cliente",
        "Anular una venta del lote actual usando su ID de operación":
            "Anular una venta del lote actual usando su ID de operación",
        "Devolver fondos usando código de autorización":
            "Devolver fondos usando código de autorización",
        "Cerrar el lote actual de transacciones":
            "Cerrar el lote actual de transacciones",
        "Imprimir duplicado usando ID de operación":
            "Imprimir duplicado usando ID de operación",
        "Obtener detalle de ventas del lote":
            "Obtener detalle de ventas del lote",
      },
    ),
    'en': AppLocale(
      adbSuite: 'ADB Suite',
      analyzeApk: 'Analyze APK',
      signerSuite: 'Signing Management',
      devTools: 'Dev Tools',
      settings: 'Settings',
      screenMirror: 'Screen Mirror',
      statusConnected: 'Connected',
      statusDisconnected: 'Disconnected',
      statusError: 'Error',
      appTitle: 'ISV TOOLKIT',
      selectApk: 'Select APK to analyze',
      analyzing: 'Analyzing...',
      fastInstall: 'Fast Install',
      install: 'INSTALL',
      delete: 'DELETE',
      packageToDelete: 'Package to delete',
      language: 'Language',
      theme: 'Theme',
      about: 'About',
      version: 'Version',
      developedBy: 'Developed by iOnetech',
      copySuccess: 'copied',
      keyAlias: 'Key Alias',
      password: 'Password',
      organization: 'Organization',
      createJks: 'NEW JKS',
      apkSigner: 'APK-SIGNER',
      jarSigner: 'JAR-SIGNER',
      debugRun: 'PROJECT (DEBUG)',
      releaseBuild: 'EXE (RELEASE)',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      rebootPos: 'Reboot POS',
      confirmReboot: 'Are you sure you want to reboot the POS?',
      toolsLoaded: 'Tools loaded',
      autoDetect: 'AUTO-DETECTION',
      exitCode: 'Exit code',
      apkSelected: 'Selected APK',
      searchHint: 'Search...',
      filter: 'FILTERS',
      startStream: 'START',
      stopStream: 'STOP',
      clearLogs: 'CLEAR',
      saveLogs: 'Save Logcat',
      signingManagement: 'Signing Management',
      signApk: 'Sign APK',
      creationCardTitle: 'JKS CONFIGURATION',
      newJks: 'Create JKS',
      apkSelectedTitle: 'Selected APK',
      pickApk: 'Browse',
      pickJks: 'Select Keystore',
      aliasLabel: 'Key Alias',
      passwordLabel: 'Keystore Password',
      ownerInfo: 'OWNER INFORMATION',
      fullName: 'Full Name',
      department: 'Department',
      company: 'Company',
      city: 'City',
      state: 'State/Province',
      countryCode: 'Country Code (US, UK...)',
      generateJks: 'Generate JKS',
      sign: 'Sign',
      cancel: 'Cancel',
      ready: 'Ready to start',
      success: 'Success',
      error: 'Error',
      copySn: 'Click to copy S/N',
      connectionStatus: 'Connection Status',
      selectTerminalTooltip: 'Select Terminal',
      validAndroid: 'Valid (Android Default)',
      validMaxStore: 'Valid (MaxStore Compatible)',
      invalidUnsigned: 'Invalid / Unsigned',
      signError: 'Error signing',
      jksSaved: 'JKS saved in:',
      jksError: 'Error creating JKS',
      apkSaved: 'Saved in:',
      missingData: 'Missing required data (APK, JKS or Password).',
      browse: 'Browse',
      signingApp: 'Sign Application',
      signingCredentials: 'Signing Credentials',
      selectApkHint: 'Select an APK file',
      selectJksHint: 'Select .jks or .keystore...',
      loading: 'Loading...',
      unavailable: 'N/A',
      close: 'CLOSE',
      architecture: 'Architecture',
      filename: 'Filename',
      schemes: 'Schemes',
      signature: 'Signature',
      viewCommands: 'View used commands',
      analyzeAnotherApk: 'Analyze another APK',
      clickToCopy: 'Click to copy',
      clearScreen: 'Clear Screen',
      autoScroll: 'Auto-scroll',
      saveLog: 'Save Log',
      configSdk: 'SDK Configuration',
      readyToStart: 'Ready to start',
      jksFileLabel: 'Filename (.jks)',
      aliasHint: 'Default: key0',
      min6Chars: 'Min 6 characters',
      repeatPassword: 'Repeat password',
      confirmPassword: 'Confirm Password',
      ownerDetails: 'OWNER DETAILS',
      certFieldsNote:
          '* These fields will appear in the APK\'s digital certificate.',
      copyIcon: 'Click to copy icon',
      copyPackage: 'Click to copy Package Name',
      copyName: 'Click to copy name',
      updateTooltip: 'Update to the APK version',
      signTooltip: 'Sign this APK',
      certificate: 'Certificate',
      sha256: 'SHA-256',
      noIcon: 'No icon',
      iconCopied: 'Icon copied to clipboard',
      iconCopyError: 'Error copying icon',
      iconCriticalError: 'Critical error copying icon',
      copied: 'Copied',
      splashLoading: 'Starting system...',
      analysisInitialTitle: 'APK Analysis',
      analysisInitialDesc:
          'Select or drag an APK to begin the technical analysis.',
      pleaseWait: 'Please wait...',
      appAlreadyInstalled: 'App is already installed',
      installApkTooltip: 'Install APK on device',
      uninstallApkTooltip: 'Uninstall app from device',
      uninstallAnyAppTooltip: 'Uninstall any app from device',
      appNotInstalled: 'App is not installed',
      splashMessages: [
        'Loading ADB modules...',
        'Starting analysis suite...',
        'Configuring signing tools...',
        'Checking device connections...',
        'Preparing workspace...',
      ],
      translations: {
        "Español": "Spanish",
        "English": "English",
        "Português": "Portuguese",
        "Configuración de Rutas": "Tools Configuration",
        "Recargar": "Reload",
        "Estadísticas": "Statistics",
        "Buscar (mín. 3 letras)...": "Search (min. 3 letters)...",
        "FILTRAR POR PACKAGE:": "FILTER BY PACKAGE:",
        "Desinstalar app del dispositivo": "Uninstall app from device",
        "La app no está instalada": "The app is not installed",
        "Cargando...": "Loading...",
        "No disponible": "N/A",
        "INSTALAR": "INSTALL",
        "DESINSTALAR": "UNINSTALL",
        "INSTALANDO...": "INSTALLING...",
        "DESINSTALANDO...": "UNINSTALLING...",
        "ACTUALIZAR": "UPDATE",
        "ACTUALIZANDO...": "UPDATING...",
        "Instalada": "Installed",
        "No instalada": "Not Installed",
        "FIRMAR": "SIGN",
        "ESPECIFICACIONES": "SPECIFICATIONS",
        "VERIFICACIÓN DE SEGURIDAD": "SECURITY CHECK",
        "LOGCAT MONITOR": "LOGCAT",
        "INICIAR STREAM": "START",
        "DETENER": "STOP",
        "LIMPIAR": "CLEAR",
        "FILTROS": "FILTERS",
        "Guardar Logcat": "Save Logcat",
        "Seleccionar APK para analizar": "Select APK to analyze",
        "Analizando...": "Analyzing...",
        "Limpiar análisis": "Clear analysis",
        "Comandos de Análisis": "Analysis Commands",
        "CERRAR": "CLOSE",
        "ESTADÍSTICAS EN VIVO": "LIVE STATISTICS",
        "Selecciona un paquete": "Select a package",
        "NUEVO JKS": "NEW JKS",
        "Monitoreo: ACTIVO": "Monitoring: ACTIVE",
        "Monitoreo: INACTIVO": "Monitoring: INACTIVE",
        "Herramientas cargadas": "Tools loaded",
        "AUTO-DETECCIÓN": "AUTO-DETECTION",
        "BUSCAR SDK": "SEARCH SDK",
        "Confirmar Reinicio": "Confirm Reboot",
        "¿Estás seguro de que deseas reiniciar el POS vinculado por ADB?":
            "Are you sure you want to reboot the POS linked via ADB?",
        "CANCELAR": "CANCEL",
        "REINICIAR": "REBOOT",
        "Alias de la Llave": "Key Alias",
        "Contraseña del Almacén": "Keystore Password",
        "JKS creado con éxito": "JKS created successfully",
        "Error al crear JKS": "Error creating JKS",
        "Comando de reinicio enviado": "Reboot command sent",
        "Error al intentar reiniciar el terminal":
            "Error trying to reboot the terminal",
        "Reiniciar Terminal": "Reboot Terminal",
        "Reiniciar POS conectado por ADB": "Reboot POS connected via ADB",
        "Selecciona una aplicación para ver estadísticas":
            "Select an application to view statistics",
        "TODOS (Escribe para buscar)": "ALL (Type to search)",
        "Herramientas de Terminal": "Terminal Tools",
        "Confirmar desinstalación": "Confirm Uninstall",
        "¿Desinstalar": "Uninstall",
        "del dispositivo?": "from device?",
        "Desinstalado con éxito": "Successfully uninstalled",
        "Error al desinstalar": "Error uninstalling",
        "Cargando paquetes...": "Loading packages...",
        "paquetes instalados": "packages installed",
        "Verificación Jarsigner": "Jarsigner Verification",
        "Firma Completa": "Fully Signed",
        "Sin Firmar (Unsigned)": "Unsigned",
        "Simulador SDK": "SDK Simulator",
        "Modo de Operación": "Operation Mode",
        "Simulador Local (MOCK)": "Local Simulator (MOCK)",
        "Terminal Físico (Vía Agente SDK)": "Physical Terminal (via SDK Agent)",
        "Host / IP": "Host / IP",
        "Puerto": "Port",
        "Puerto COM": "COM Port",
        "Estado del Terminal": "Terminal Status",
        "Consola de Logs": "Logs Console",
        "Respuesta del Terminal": "Terminal Response",
        "Monto": "Amount",
        "Propina": "Tip",
        "Tipo de Pago": "Payment Type",
        "Cuotas": "Installments",
        "ID de Orden": "Order ID",
        "Enviar Transacción": "Send Transaction",
        "Limpiar": "Clear",
        "Historial de Operaciones": "Operations History",
        "Conectando...": "Connecting...",
        "Espere por favor...": "Please wait...",
        "Monto inválido": "Invalid amount",
        "RUT inválido": "Invalid RUT",
        "Transacción enviada": "Transaction sent",
        "Ingresa el ID de la transacción a anular":
            "Enter the transaction ID to void",
        "Última venta": "Last sale",
        "Copiar JSON": "Copy JSON",
        "Copiar logs": "Copy logs",
        "Venta": "Sale",
        "Anulación": "Cancellation",
        "Conectar": "Connect",
        "Desconectar": "Disconnect",
        "Número de Ticket": "Ticket Number",
        "Tipo de Venta": "Sale Type",
        "ID de Vendedor": "Employee ID",
        "Imprimir en POS": "Print on POS",
        "Mensajes Intermedios": "Send Messages",
        "Timeout (segundos)": "Timeout (seconds)",
        "Test conexión (POLL)": "Connection Test (POLL)",
        "Ejecutando POLL...": "Executing POLL...",
        "Ping de conexión exitoso": "Connection ping successful",
        "Error al ejecutar POLL": "Error executing POLL",
        "Última transacción": "Last transaction",
        "Firma digital": "Digital signature",
        "JSON serializado": "Serialized JSON",
        "Otro...": "Other...",
        "Mostrar lista": "Show list",
        "Devolución (103)": "Refund (103)",
        "Pre-Autorización (104)": "Pre-Authorization (104)",
        "Confirmar Pre-Aut (105)": "Confirm Pre-Auth (105)",
        "POLL (106)": "POLL (106)",
        "Última Transacción (108)": "Last Transaction (108)",
        "Ver Configuración (110)": "View Configuration (110)",
        "Reporte Propinas (111)": "Tips Report (111)",
        "Saldo (112)": "Balance (112)",
        "Totales Lote (121)": "Batch Totals (121)",
        "Detalle Transacciones (123)": "Tx Details (123)",
        "Reporte Vendedor (125)": "Seller Report (125)",
        "Modo Normal (107)": "Normal Mode (107)",
        "Cierre (120)": "Close Batch (120)",
        "Inicializar (122)": "Initialize (122)",
        "Duplicado (124)": "Print Duplicate (124)",
        "Parámetros (126)": "Parameters (126)",
        "Test Comm (128)": "Comm Test (128)",
        "Bajar Llaves (130)": "Download Keys (130)",
        "Transacciones": "Transactions",
        "Consultas": "Queries",
        "Gestión": "Management",
        "Monto Devolución": "Refund Amount",
        "Monto Pre-Autorización": "Pre-Auth Amount",
        "Monto Confirmación": "Confirmation Amount",
        "Clave (Key)": "Key",
        "Valor (Value)": "Value",
        "ID de Transacción Original": "Original Transaction ID",
        "Este comando se enviará directamente al POS sin parámetros adicionales.":
            "This command will be sent directly to the POS without additional parameters.",
        "Enviar Comando": "Send Command",
        "Consulta": "Poll",
        "Último comprobante": "Last Voucher",
        "Cierre": "Close",
        "Duplicado / Reimpresión": "Duplicate / Reprint",
        "Detalles": "Details",
        "Cancelar venta": "Cancel Sale",
        "Totales": "Totals",
        "Modo normal": "Normal Mode",
        "Reembolso / Devolución": "Refund",
        "Ventas por vendedor": "Seller Sales",
        "Informe de propinas": "Tips Report",
        "Venta predeterminada": "Default Sale",
        "Parámetros": "Params",
        "Informe SIM": "SIM Report",
        "Devolución": "Refund",

        "Venta MC": "Sale MC",
        "Anulación MC": "Cancellation MC",
        "Reembolso MC": "Refund MC",
        "Datos principales del POS": "Main POS Data",
        "ID de Transacción a Duplicar": "Transaction ID to Duplicate",
        "Código de Autorización": "Authorization Code",
        "Código de Comercio": "Commerce Code",
        "Tipo de Venta Predeterminada": "Default Sale Type",
        "FILTRO DE BÚSQUEDA": "SEARCH FILTER",
        "ID de Transacción a Anular": "Transaction ID to Void",
        "Protocolo Simplificado": "Simplified Protocol",
        "Texto a Hexadecimal": "Text to Hexadecimal",
        "Hexadecimal a Texto": "Hexadecimal to Text",
        "CONVERSOR / LRC": "CONVERTER / LRC",
        "Paso 1: Seleccione la conversión": "Step 1: Select Conversion",
        "Paso 2: Ingrese la data (Excluyendo STX/ETX/LRC)":
            "Step 2: Enter Data (Excluding STX/ETX/LRC)",
        "Paso 3: Resultado de conversión": "Step 3: Conversion Result",
        "Traducción Real (Bytes de Control 0x02, 0x03)":
            "Real Transmission (Control Bytes 0x02, 0x03)",
        "Traducción Literal (String \"<STX>\", \"<ETX>\")":
            "Literal Translation (String \"<STX>\", \"<ETX>\")",
        "Hex copiado al portapapeles": "Hex copied to clipboard",
        "ENVIAR VENTA (ISO8583)": "SEND SALE (ISO8583)",
        "Enviar Venta Simplificada": "Send Simplified Sale",
        "Venta aprobada en Protocolo Simplificado!":
            "Sale approved in Simplified Protocol!",
        "Venta rechazada/fallida": "Sale rejected/failed",
        "OPCIONES DE IMPRESIÓN": "PRINT OPTIONS",
        "CONEXIÓN PUERTO SERIAL": "SERIAL PORT CONNECTION",
        "Comunicación basada en el formato ISO8583 (Pipe Separated)":
            "Communication based on ISO8583 format (Pipe Separated)",
        "Terminal conectado en": "Terminal connected on",
        "Error al conectar en": "Error connecting on",
        "Debe conectar el puerto COM primero.":
            "You must connect the COM port first.",
        "Código": "Code",
        "ENVIAR COMANDO (ISO8583)": "SEND COMMAND (ISO8583)",
        "Comando a enviar": "Command to send",
        "Enviar Comando Simplificado": "Send Simplified Command",
        "Usar última venta": "Use last sale",
        "Comando rechazado/fallido": "Command rejected/failed",
        "Realizar una venta cobrando al cliente":
            "Perform a sale charging the client",
        "Anular una venta del lote actual usando su ID de operación":
            "Void a sale from current batch using its operation ID",
        "Devolver fondos usando código de autorización":
            "Refund funds using authorization code",
        "Cerrar el lote actual de transacciones":
            "Close the current batch of transactions",
        "Imprimir duplicado usando ID de operación":
            "Print duplicate using operation ID",
        "Obtener detalle de ventas del lote": "Get batch sales details",
      },
    ),
    'pt': AppLocale(
      adbSuite: 'Suite ADB',
      analyzeApk: 'Analisar APK',
      signerSuite: 'Gestão de Assinatura',
      devTools: 'Ferramentas Dev',
      settings: 'Configurações',
      screenMirror: 'Espelho de Tela',
      statusConnected: 'Conectado',
      statusDisconnected: 'Desconectado',
      statusError: 'Erro',
      appTitle: 'ISV TOOLKIT',
      selectApk: 'Selecionar APK para analizar',
      analyzing: 'Analisando...',
      fastInstall: 'Instalação Rápida',
      install: 'INSTALAR',
      delete: 'APAGAR',
      packageToDelete: 'Pacote para apagar',
      language: 'Idioma',
      theme: 'Tema',
      about: 'Sobre',
      version: 'Versão',
      developedBy: 'Desenvolvido por iOnetech',
      copySuccess: 'copiado',
      keyAlias: 'Alias da Chave',
      password: 'Senha',
      organization: 'Organização',
      createJks: 'NOVO JKS',
      apkSigner: 'APK-SIGNER',
      jarSigner: 'JAR-SIGNER',
      debugRun: 'PROJETO (DEBUG)',
      releaseBuild: 'EXE (RELEASE)',
      darkMode: 'Modo Escuro',
      lightMode: 'Modo Claro',
      rebootPos: 'Reiniciar POS',
      confirmReboot: 'Tem certeza que deseja reiniciar o POS?',
      toolsLoaded: 'Ferramentas carregadas',
      autoDetect: 'AUTO-DETECÇÃO',
      exitCode: 'Código de saída',
      apkSelected: 'APK Selecionado',
      searchHint: 'Procurar...',
      filter: 'FILTROS',
      startStream: 'INICIAR',
      stopStream: 'PARAR',
      clearLogs: 'LIMPAR',
      saveLogs: 'Salvar Logcat',
      signingManagement: 'Gestão de Assinatura',
      signApk: 'Assinar APK',
      creationCardTitle: 'CONFIGURAÇÃO JKS',
      newJks: 'Criar JKS',
      apkSelectedTitle: 'APK Selecionado',
      pickApk: 'Explorar',
      pickJks: 'Selecionar Armazém',
      aliasLabel: 'Alias da Chave',
      passwordLabel: 'Senha do Armazém',
      ownerInfo: 'INFORMAÇÃO DO PROPRIETÁRIO',
      fullName: 'Nome Completo',
      department: 'Departamento',
      company: 'Empresa',
      city: 'Cidade',
      state: 'Estado/Província',
      countryCode: 'Código do País (PT, BR...)',
      generateJks: 'Gerar JKS',
      sign: 'Assinar',
      cancel: 'Cancelar',
      ready: 'Pronto para iniciar',
      success: 'Sucesso',
      error: 'Erro',
      copySn: 'Clique para copiar S/N',
      connectionStatus: 'Status da conexão',
      selectTerminalTooltip: 'Selecionar Terminal',
      validAndroid: 'Válida (Padrão Android)',
      validMaxStore: 'Válida (Compatível com MaxStore)',
      invalidUnsigned: 'Inválida / Não assinada',
      signError: 'Erro ao assinar',
      jksSaved: 'JKS salvo em:',
      jksError: 'Erro ao criar JKS',
      apkSaved: 'Salvo em:',
      missingData: 'Faltam dados necessários (APK, JKS ou Senha).',
      browse: 'Explorar',
      signingApp: 'Assinar Aplicativo',
      signingCredentials: 'Credenciais de Assinatura',
      selectApkHint: 'Selecione um archivo APK',
      selectJksHint: 'Selecionar .jks ou .keystore...',
      loading: 'Carregando...',
      unavailable: 'Não disponible',
      close: 'FECHAR',
      architecture: 'Arquitetura',
      filename: 'Nome do Arquivo',
      schemes: 'Esquemas',
      signature: 'Assinatura',
      viewCommands: 'Ver comandos usados',
      analyzeAnotherApk: 'Analisar outro APK',
      clickToCopy: 'Clique para copiar',
      clearScreen: 'Limpar Tela',
      autoScroll: 'Auto-scroll',
      saveLog: 'Salvar Log',
      configSdk: 'Configuração SDK',
      readyToStart: 'Pronto para iniciar',
      jksFileLabel: 'Nome do arquivo (.jks)',
      aliasHint: 'Padrão: key0',
      min6Chars: 'Mínimo 6 caracteres',
      repeatPassword: 'Repita a senha',
      confirmPassword: 'Confirmar Senha',
      ownerDetails: 'DETALHES DO PROPRIETÁRIO',
      certFieldsNote:
          '* Estes campos aparecerão no certificado digital da APK.',
      copyIcon: 'Clique para copiar o ícone',
      copyPackage: 'Clique para copiar o Package Name',
      copyName: 'Clique para copiar o nome',
      updateTooltip: 'Atualizar para a versão da APK',
      signTooltip: 'Assinar esta APK',
      certificate: 'Certificado',
      sha256: 'SHA-256',
      noIcon: 'Sem ícone',
      iconCopied: 'Ícone copiado para a área de transferência',
      iconCopyError: 'Erro ao copiar ícone',
      iconCriticalError: 'Erro crítico ao copiar ícone',
      copied: 'Copiado',
      splashLoading: 'Iniciando sistema...',
      analysisInitialTitle: 'Análise de APK',
      analysisInitialDesc:
          'Selecione ou arraste um APK para iniciar a análise técnica.',
      pleaseWait: 'Por favor, aguarde...',
      appAlreadyInstalled: 'O app já está instalado',
      installApkTooltip: 'Instalar APK no dispositivo',
      uninstallApkTooltip: 'Desinstalar app do dispositivo',
      uninstallAnyAppTooltip: 'Desinstalar qualquer app do dispositivo',
      appNotInstalled: 'O app não está instalado',
      splashMessages: [
        'Carregando módulos ADB...',
        'Iniciando suíte de análise...',
        'Configurando ferramentas de assinatura...',
        'Verificando conexão com dispositivos...',
        'Preparando ambiente de trabalho...',
      ],
      translations: {
        "Español": "Espanhol",
        "English": "Inglês",
        "Português": "Português",
        "Configuración de Rutas": "Configuração de Rotas",
        "Recargar": "Recarregar",
        "Estadísticas": "Estatísticas",
        "Buscar (mín. 3 letras)...": "Procurar (mín. 3 letras)...",
        "FILTRAR POR PACKAGE:": "FILTRAR POR PACOTE:",
        "Desinstalar app del dispositivo": "Desinstalar app do dispositivo",
        "La app no está instalada": "O aplicativo não está instalado",
        "Cargando...": "Carregando...",
        "No disponible": "Não disponível",
        "INSTALAR": "INSTALAR",
        "DESINSTALAR": "DESINSTALAR",
        "INSTALANDO...": "INSTALANDO...",
        "DESINSTALANDO...": "DESINSTALANDO...",
        "ACTUALIZAR": "ATUALIZAR",
        "ACTUALIZANDO...": "ATUALIZANDO...",
        "Instalada": "Instalada",
        "No instalada": "Não instalada",
        "FIRMAR": "ASSINAR",
        "ESPECIFICACIONES": "ESPECIFICAÇÕES",
        "VERIFICACIÓN DE SEGURIDAD": "VERIFICAÇÃO DE SEGURANÇA",
        "LOGCAT MONITOR": "LOGCAT",
        "INICIAR STREAM": "INICIAR",
        "DETENER": "PARAR",
        "LIMPIAR": "LIMPAR",
        "FILTROS": "FILTROS",
        "Guardar Logcat": "Salvar Logcat",
        "Seleccionar APK para analizar": "Selecionar APK para analisar",
        "Analizando...": "Analisando...",
        "Limpiar análise": "Limpar análise",
        "Comandos de Análisis": "Comandos de Análise",
        "CERRAR": "FECHAR",
        "ESTADÍSTICAS EN VIVO": "ESTATÍSTICAS AO VIVO",
        "Selecciona un paquete": "Selecione um pacote",
        "NUEVO JKS": "NOVO JKS",
        "Monitoreo: ACTIVO": "Monitoramento: ATIVO",
        "Monitoreo: INACTIVO": "Monitoramento: INATIVO",
        "Herramientas cargadas": "Ferramentas cargadas",
        "AUTO-DETECCIÓN": "AUTO-DETECÇÃO",
        "BUSCAR SDK": "PROCURAR SDK",
        "Confirmar Reinicio": "Confirmar Reinício",
        "¿Estás seguro de que deseas reiniciar el POS vinculado por ADB?":
            "Tem certeza que deseja reiniciar o POS vinculado pelo ADB?",
        "CANCELAR": "CANCELAR",
        "REINICIAR": "REINICIAR",
        "Alias de la Llave": "Alias da Chave",
        "Contraseña del Almacén": "Senha do Armazém",
        "JKS creado con éxito": "JKS creado com sucesso",
        "Error al crear JKS": "Erro ao criar JKS",
        "Comando de reinicio enviado": "Comando de reinicialização enviado",
        "Error al intentar reiniciar el terminal":
            "Erro ao tentar reiniciar o terminal",
        "Reiniciar Terminal": "Reiniciar Terminal",
        "Reiniciar POS conectado por ADB": "Reiniciar POS conectado via ADB",
        "Selecciona una aplicación para ver estadísticas":
            "Selecione um aplicativo para ver estatísticas",
        "TODOS (Escribe para buscar)": "TODOS (Escreva para pesquisar)",
        "Espejo de Pantalla": "Espelho de Tela",
        "Iniciar Espejo": "Iniciar Espelho",
        "Mirroring: ACTIVO": "Mirroring: ATIVO",
        "Mirroring: INACTIVO": "Mirroring: INATIVO",
        "Descargando scrcpy...": "Baixando scrcpy...",
        "Instalando scrcpy...": "Instalando scrcpy...",
        "Herramientas Mirror cargadas": "Ferramentas Mirror carregadas",
        "Descarga completada": "Download concluído",
        "Herramientas de Terminal": "Ferramentas de Terminal",
        "Confirmar desinstalación": "Confirmar Desinstalação",
        "¿Desinstalar": "Desinstalar",
        "del dispositivo?": "do dispositivo?",
        "Desinstalado con éxito": "Desinstalado com sucesso",
        "Error al desinstalar": "Erro ao desinstalar",
        "Cargando paquetes...": "Carregando pacotes...",
        "paquetes instalados": "pacotes instalados",
        "Verificación Jarsigner": "Verificação Jarsigner",
        "Firma Completa": "Assinatura Completa",
        "Sin Firmar (Unsigned)": "Sem Assinatura (Unsigned)",
        "Simulador SDK": "Simulador SDK",
        "Modo de Operación": "Modo de Operação",
        "Simulador Local (MOCK)": "Simulador Local (MOCK)",
        "Terminal Físico (Vía Agente SDK)": "Terminal Físico (Via Agente SDK)",
        "Host / IP": "Host / IP",
        "Puerto": "Porta",
        "Puerto COM": "Porta COM",
        "Estado del Terminal": "Status do Terminal",
        "Consola de Logs": "Console de Logs",
        "Respuesta del Terminal": "Resposta del Terminal",
        "Monto": "Valor",
        "Propina": "Gorjeta",
        "Tipo de Pago": "Tipo de Pagamento",
        "Cuotas": "Parcelas",
        "ID de Orden": "ID do Pedido",
        "Enviar Transacción": "Enviar Transação",
        "Limpiar": "Limpar",
        "Historial de Operaciones": "Histórico de Operações",
        "Conectando...": "Conectando...",
        "Espere por favor...": "Por favor, aguarde...",
        "Monto inválido": "Valor inválido",
        "RUT inválido": "RUT inválido",
        "Transacción enviada": "Transação enviada",
        "Ingresa el ID de la transacción a anular":
            "Insira o ID da transação a anular",
        "Última venta": "Última venda",
        "Copiar JSON": "Copiar JSON",
        "Copiar logs": "Copiar logs",
        "Venta": "Venda",
        "Anulación": "Anulação",
        "Conectar": "Conectar",
        "Desconectar": "Desconectar",
        "Número de Ticket": "Número do Ticket",
        "Tipo de Venta": "Tipo de Venda",
        "ID de Vendedor": "ID do Vendedor",
        "Imprimir en POS": "Imprimir no POS",
        "Mensajes Intermedios": "Mensagens Intermediárias",
        "Timeout (segundos)": "Timeout (segundos)",
        "Test conexión (POLL)": "Teste de Conexão (POLL)",
        "Ejecutando POLL...": "Executando POLL...",
        "Ping de conexión exitoso": "Ping de conexão bem-sucedido",
        "Error al ejecutar POLL": "Erro ao executar POLL",
        "Última transacción": "Última transação",
        "Firma digital": "Assinatura digital",
        "JSON serializado": "JSON serializado",
        "Otro...": "Outro...",
        "Mostrar lista": "Mostrar lista",
        "Devolución (103)": "Devolução (103)",
        "Pre-Autorización (104)": "Pré-Autorização (104)",
        "Confirmar Pre-Aut (105)": "Confirmar Pré-Aut (105)",
        "POLL (106)": "POLL (106)",
        "Última Transacción (108)": "Última Transação (108)",
        "Ver Configuración (110)": "Ver Configurações (110)",
        "Reporte Propinas (111)": "Relatório Gorjetas (111)",
        "Saldo (112)": "Saldo (112)",
        "Totales Lote (121)": "Totais do Lote (121)",
        "Detalle Transacciones (123)": "Detalhe Transações (123)",
        "Reporte Vendedor (125)": "Relatório Vendedor (125)",
        "Modo Normal (107)": "Modo Normal (107)",
        "Cierre (120)": "Fechamento (120)",
        "Inicializar (122)": "Inicializar (122)",
        "Duplicado (124)": "Duplicado (124)",
        "Parámetros (126)": "Parâmetros (126)",
        "Test Comm (128)": "Teste de Comm (128)",
        "Bajar Llaves (130)": "Baixar Chaves (130)",
        "Transacciones": "Transações",
        "Consultas": "Consultas",
        "Gestión": "Gestão",
        "Monto Devolución": "Valor Devolução",
        "Monto Pre-Autorización": "Valor Pré-Autorização",
        "Monto Confirmación": "Valor Confirmação",
        "Clave (Key)": "Chave",
        "Valor (Value)": "Valor",
        "ID de Transacción Original": "ID da Transação Original",
        "Este comando se enviará directamente al POS sin parámetros adicionales.":
            "Este comando será enviado diretamente ao POS sem parâmetros adicionais.",
        "Enviar Comando": "Enviar Comando",
        "Consulta": "Consulta",
        "Último comprobante": "Último comprovante",
        "Cierre": "Fechamento",
        "Duplicado / Reimpresión": "Duplicado",
        "Detalles": "Detalhes",
        "Cancelar venta": "Cancelar venda",
        "Totales": "Totais",
        "Modo normal": "Modo normal",
        "Reembolso / Devolución": "Reembolso / Devolução",
        "Ventas por vendedor": "Vendas por vendedor",
        "Informe de propinas": "Relatório de gorjetas",
        "Venta predeterminada": "Venda padrão",
        "Parámetros": "Parâmetros",
        "Informe SIM": "Relatório SIM",
        "Venta MC": "Venda MC",
        "Anulación MC": "Anulação MC",
        "Devolución MC": "Devolução MC",
        "Datos principales del POS": "Dados principais do POS",
        "ID de Transacción a Duplicar": "ID da Transação a Duplicar",
        "Código de Autorización": "Código de Autorização",
        "Código de Comercio": "Código de Comércio",
        "Tipo de Venta Predeterminada": "Tipo de Venda Padrão",
        "FILTRO DE BÚSQUEDA": "FILTRO DE BUSCA",
        "ID de Transacción a Anular": "ID da Transação a Anular",
        "Protocolo Simplificado": "Protocolo Simplificado",
        "Texto a Hexadecimal": "Texto para Hexadecimal",
        "Hexadecimal a Texto": "Hexadecimal para Texto",
        "CONVERSOR / LRC": "CONVERTER / LRC",
        "Paso 1: Seleccione la conversión": "Passo 1: Selecione a conversão",
        "Paso 2: Ingrese la data (Excluyendo STX/ETX/LRC)":
            "Passo 2: Insira os dados (Excluindo STX/ETX/LRC)",
        "Paso 3: Resultado de conversión": "Passo 3: Resultado da conversão",
        "Traducción Real (Bytes de Control 0x02, 0x03)":
            "Tradução Real (Bytes de Controle 0x02, 0x03)",
        "Traducción Literal (String \"<STX>\", \"<ETX>\")":
            "Tradução Literal (String \"<STX>\", \"<ETX>\")",
        "Hex copiado al portapapeles":
            "Hex copiado para a área de transferência",
        "ENVIAR VENTA (ISO8583)": "ENVIAR VENDA (ISO8583)",
        "Enviar Venta Simplificada": "Enviar Venda Simplificada",
        "Venta aprobada en Protocolo Simplificado!":
            "Venda aprovada no Protocolo Simplificado!",
        "Venta rechazada/fallida": "Venda rejeitada/falhada",
        "OPCIONES DE IMPRESIÓN": "OPÇÕES DE IMPRESSÃO",
        "CONEXIÓN PUERTO SERIAL": "CONEXÃO DA PORTA SERIAL",
        "Comunicación basada en el formato ISO8583 (Pipe Separated)":
            "Comunicação baseada no formato ISO8583 (Separada por Pipe)",
        "Terminal conectado en": "Terminal conectado em",
        "Error al conectar en": "Erro ao conectar em",
        "Debe conectar el puerto COM primero.":
            "Você deve conectar a porta COM primeiro.",
        "Código": "Código",
        "ENVIAR COMANDO (ISO8583)": "ENVIAR COMANDO (ISO8583)",
        "Comando a enviar": "Comando a enviar",
        "Enviar Comando Simplificado": "Enviar Comando Simplificado",
        "Usar última venta": "Usar última venda",
        "Comando rechazado/fallido": "Comando rejeitado/falhado",
        "Realizar una venta cobrando al cliente":
            "Realizar uma venda cobrando o cliente",
        "Anular una venta del lote actual usando su ID de operación":
            "Cancelar uma venda do lote atual usando seu ID de operação",
        "Devolver fondos usando código de autorización":
            "Devolver fundos usando o código de autorização",
        "Cerrar el lote actual de transacciones":
            "Fechar o lote atual de transações",
        "Imprimir duplicado usando ID de operação":
            "Imprimir duplicado usando o ID de operação",
        "Obtener detalle de ventas del lote":
            "Obter detalhes das vendas do lote",
      },
    ),
  };
}

extension AppLocaleTranslation on AppLocale {
  String t(String key) {
    return translations[key] ?? key;
  }
}
